### ISSUE TITLE
yarn failed

### ISSUE THREAD

**Issue by HatalDev** [vicary/react-native-citizen-escposprinter#10]
@vicary when I'm adding the new version via yarn I'm getting the following error

`error /Users/user/Developer/project/node_modules/react-native-citizen-escposprinter: Command failed.
Exit code: 127
Command: bob build
Arguments: 
Directory: /Users/user/Developer/project/node_modules/react-native-citizen-escposprinter
Output:
/bin/sh: bob: command not found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Comment by vicary** [comment]
@HatalDev please try again with 0.4.1
